const languages = {
    en: {
        title_page: "Tamrini",
        home: "Home",
        about: "About us",
        advantages: "Advantages",
        gallery: "Gallery",
        stats: "Stats",
        contact: "Contact",
        land_info: "Will Work out now through the best application for gym and fitness it will provide you with all you need for a fit well-built body.",
        land_get: "Download Now",
        about_main_title: "About us",
        about_info: "Being in a good shape through home excercises is now possible for everybody and without internet Are you looking for a perfect body do you want muscles ever dreamed of a perfect shape but you have no equipments do you want nutritional complements at competetive prices do you want a personal trainer?",
        about_get: "Get the app now",
        advantages_main_title: "Advantages",
        advantages_second_title: "Some features of the app that will make you addicted to using it :",
        advantages_second_title_p: "This app has been developed to cater for the needs of everyone of all types and stripes; whether you are a beginner, a professional body builder, or just interested in nutrition this app is your best go to.",
        advantages_col_title_1: "Easy home excercises without net or equipments",
        advantages_col_p_1: "The app offers diversified home excercises with pictures and video tutorials like back and butt excercises, chest excercises, stomach excercises, excercises to lose weight or increase your height, arm excercises, plank excercises and more to explore",
        advantages_col_title_2: "Health and nutrition",
        advantages_col_p_2: "The app gives special care for your health as it provides you with all the requirements such as calories and protein calculator , it also allows you to know the nutritional value of many vegetables and fruits as well as the nutritional complements and how to best use them",
        advantages_col_title_3: "Educate yourself",
        advantages_col_p_3: "Written by professional trainers and certified nutrition experts, the app contains articles revealing all the secrets of body building, stamina, nutrition and many more",
        advantages_col_title_4: "Nutritional complements, proteins and fat burners store",
        advantages_col_p_4: "The app offers high quality nutritional complements that everyone needs to build the perfect body at very competetive prices",
        advantages_col_title_5: "Find the closest gym to you",
        advantages_col_p_5: "The app navigates the closest gyms to your home and will automatically lead you to them through gps",
        advantages_col_title_6: "Follow up with professional trainers",
        advantages_col_p_6: "One of the main features of the app is enabling you to get through professional trainers and collaborating with them to develop your stamina and realise your fitness goals.",
        advantages_get: "What are you waiting for !! download the app now and get the best professional trainer",
        gallery_main_title: "Gallery",
        stats_main_title: "Stats",
        stats_box_1: "Training",
        stats_box_2: "Home Training",
        stats_box_3: "Dietary Supplement",
        stats_box_4: "Sports Club",
        stats_box_5: "Article",
        stats_box_6: "Diet food",
        stats_box_7: "Nutritional values of food",
        stats_box_8: "Application downloads",
        stats_box_9: "Users Signup",
        stats_box_10: "Coach in the app",
        contact_main_title: "Contact",
        contact_whats_title: "Whatsapp",
        contact_whats_mess: "Send a message",
        contact_email_title: "Email",
        contact_email_mess: "Send a email",
    },
    ar: {
        title_page: "تمريني دليل كمال الاجسام",
        home: "الرئيسية",
        about: "معلومات عنا",
        advantages: "مميزاتنا",
        gallery: "معرضنا",
        stats: "احصائياتنا",
        contact: "اتصل بنا",
        land_info: "تمرن الان من خلال أفضل ابلكيشن للجيم والفتنس سيوفر لك كل ما تحتاجه لبناء جسم مثالي رشيق .",
        land_get: "حمل التطبيق الآن",
        about_main_title: "معلومات عنا",
        about_info: "أصبح الان بإمكان الجميع الحصول على لياقة بدنية عالية من خلال تمارين رياضية في المنزل بدون نت للرجال والنساء. هل ترغب في بناء جسم قوي ومتناسق؟ هل تريد تشكيل عضلات والبقاء في لياقة بدنية؟ هل تريد أسهل تمارين منزلية فعالة بدون نت وبدون معدات؟ هل تريد شراء مكملات غذائية بأفضل الاسعار؟ هل تحتاج الى تتبع مع مدرب شخصي ممارس؟",
        about_get: "احصل على التطبيق الآن",
        advantages_main_title: "مميزاتنا",
        advantages_second_title: "مميزات تطبيق تمريني التي ستجعلك تدمن على استخدامه:",
        advantages_second_title_p: "تم تطوير تطبيق تمريني ليناسب جميع الفئات الرياضيين المبتدئين – الرياضيين المحترفين – المهتمون باللياقة البدنية – المهتمين بالتغذية الصحية -  بشكل كامل، ألوان أفضل، وجودة اعلى، ومعلومات أكثر، وأسعار اقل.",
        advantages_col_title_1: "تمارين منزلية سهلة بدون معدات وبدون نت ",
        advantages_col_p_1: "يوفر التطبيق تمارين رياضية متنوعة في المنزل بدون نت وبالصور الفيديو مثلا تمارين الاكتاف، تمارين المؤخرة، تمارين الضهر، تمارين الصدر، تمارين البطن، تمارين زيادة الطول تمارين زيادة الوزن، تمارين الدمبل، تدريبات الذراع، تمارين بلانك، تمارين خسارة الوزن.",
        advantages_col_title_2: "الصحة والتغذية",
        advantages_col_p_2: "تطبيق تمريني يهتم بصحتكم من خلال انه يوفر لكم كل الأدوات التي يمكنك احتياجها مثل حاسبة السعرات الحرارية والبروتين، معرفة القيمة الغذائية لمجموعة من الأغذية والفواكه وستجد دليل انواع المكملات الغذائية من طرق استخدامها ومعلومات حول استخدامها.",
        advantages_col_title_3: "ثقف نفسك",
        advantages_col_p_3: "سيساعدك تطبيق تمريني على معرفة كل اسرار اللياقة البدنية والصحة من خلال مقالات ومواضيع حصرية عن اللياقة البدنية وكمال الاجسام، والتغذية الصحية وتحسين الأداء الرياضي وهذه المقالات تم انشاؤها من خبراء ومدربين معتمدين في مجال اللياقة البدنية.",
        advantages_col_title_4: "متجر كامل في المكملات الغذائية والبروتينات ",
        advantages_col_p_4: "يحتوي على العديد من أنواع المكملات الغذائية الصحية التي يحتاج اليها كل رياضي بأفضل الأسعار واعلى درجات الجودة.",
        advantages_col_title_5: "اعثر على أقرب جيم من منزلك",
        advantages_col_p_5: "يوفر لك تطبيق تمريني اقراب صلات الجيم للتمرن من خلال تفعيل الموقع الجغرافي للجهاز وسيعثر لك تلقائيا على أفضل صلات الجيم. ",
        advantages_col_title_6: "التتبع مع مدربين ممارسين",
        advantages_col_p_6: "احدى المزايا الرئيسية في التطبيق حيث يمكن للمستخدمين الاتصال بمدربين شخصيين محترفين عبر التطبيق والتعاون معهم لتحسين لياقتك البدنية وتحقيق أهدافك الرياضية.",
        advantages_get: "ماذا تنتظر قم بتنزيل التطبيق واجعله مدربك الخاص، وإذ كان لك أي سؤال يمكنك طرحه في التطبيق وسيتم الإجابة عنه من طرف مختصين في اللياقة البدنية والتدريب الرياضي مجانا.",
        gallery_main_title: "معرضنا",
        stats_main_title: "احصائياتنا",
        stats_box_1: "تمرين",
        stats_box_2: "تمرين منزلي",
        stats_box_3: "مكمل غذائي",
        stats_box_4: "نادي رياضي",
        stats_box_5: "مقال",
        stats_box_6: "اكلات دايت",
        stats_box_7: "قيمة غذائية للأكل",
        stats_box_8: "عدد تحميلات تطبيقنا",
        stats_box_9: "عدد المشتركين",
        stats_box_10: "عدد المدربين لدينا",
        contact_main_title: "اتصل بنا",
        contact_whats_title: "واتس آب",
        contact_whats_mess: "ارسل رسالة",
        contact_email_title: "ايميل",
        contact_email_mess: "ارسل ايميل",
    },
};

export default languages;